name: learn-github-actions
on: [push]
jobs:
  hello-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pwd
      - run: echo "This is our first Github Workflow!"
