name: learn-github-actions
on: push
jobs:
  hello-actions:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: hostname
      - uses: actions/checkout@v2
      - run: echo "This is our first Github Workflow!"
