<<<<<<< HEAD
name: Deployment of python app
on: pull_request
=======
name: Deployment-of-python-app
on: [push]
>>>>>>> 82f444dea0fc572d7f568d589160b4b0f2e92610
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
      - run: echo "This has been triggered ${{ github.event_name }} event"
      - run: echo "This job is running on ${{ runner.os }} server hosted on github!"
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with: 
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Lint with pylint
        run: |
          python lint_test.py
      - name: Build container
        run: |
          echo "Building a container image"
          sleep 30
      - name: Deploy to cluster
        run: |
          echo "Deploying to cluster"
          sleep 30
          echo "Container has been deployed!"
      - run: echo "This job's status is ${{ job.status }}!" 
    
  
=======
    - run: echo "this has been triggered ${{ github.event_name }} event"
    - run: echo "This job is running on ${{ runner.os }} server hosted on github!"
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Lint with pylint
      run: |
        python lint_test.py
    - name: Build container
      run: |
        echo "Building a container image..."
        sleep 30
    - name: Deploy to cluster
      run: |
        echo "Deploying to cluster..."
        sleep 30
        echo "Container has been deployed!"
    - run: echo "This job's status is ${{ job.status }}."
>>>>>>> 82f444dea0fc572d7f568d589160b4b0f2e92610
